/*
Shared names paths timeouts defaults and size limits.
*/

package constants

APP_NAME :: "nullray"
VERSION :: "0.1.0"
BUILD_DATE :: #config(NULLRAY_BUILD_DATE, "unknown")
BUILD_TIME :: #config(NULLRAY_BUILD_TIME, "unknown")
CONFIG_DIR_NAME :: "nullray"
CONFIG_FILE :: "config.ini"
MCP_CONFIG_FILE :: "mcp.json"

DEFAULT_PROVIDER :: "ollama"
DEFAULT_MODEL_OLLAMA :: "gemma3:4b"
DEFAULT_MODEL_LMSTUDIO :: "local-model"
DEFAULT_MODEL_OPENROUTER :: "google/gemini-3.8-flash"
DEFAULT_MODEL_OPENCODE :: "big-pickle"

DEFAULT_OLLAMA_BASE :: "http://127.0.0.1:11434/v1"
DEFAULT_LMSTUDIO_BASE :: "http://127.0.0.1:1234/v1"
DEFAULT_OPENROUTER_BASE :: "https://openrouter.ai/api/v1"
DEFAULT_OPENCODE_BASE :: "https://opencode.ai/zen/v1"
DEFAULT_OPENCODE_GO_BASE :: "https://opencode.ai/zen/go/v1"

DEFAULT_MODEL_OPENCODE_GO :: "minimax-m2.5"
DEFAULT_MAX_TOKENS :: 2048
DEFAULT_REASONING :: "low"

ENV_PROVIDER :: "NULLRAY_PROVIDER"
ENV_MODEL :: "NULLRAY_MODEL"
ENV_BASE_URL :: "NULLRAY_BASE_URL"
ENV_API_KEY :: "NULLRAY_API_KEY"
ENV_OLLAMA_HOST :: "OLLAMA_HOST"
ENV_LMSTUDIO_HOST :: "LM_STUDIO_HOST"
ENV_OPENROUTER_KEY :: "OPENROUTER_API_KEY"
ENV_OPENCODE_KEY :: "OPENCODE_API_KEY"
ENV_LMSTUDIO_KEY :: "LM_API_TOKEN"
ENV_COLOR :: "NULLRAY_COLOR"
ENV_THEME :: "NULLRAY_THEME"
ENV_SANDBOX :: "NULLRAY_SANDBOX"
ENV_SANDBOX_NET :: "NULLRAY_SANDBOX_NET"
ENV_SANDBOX_FS :: "NULLRAY_SANDBOX_FS"
ENV_PRIVACY :: "NULLRAY_PRIVACY"
ENV_SECCOMP :: "NULLRAY_SECCOMP"
ENV_LANDLOCK :: "NULLRAY_LANDLOCK"
ENV_WORKSPACE :: "NULLRAY_WORKSPACE"
ENV_TMPDIR :: "NULLRAY_TMPDIR"
ENV_AGENT_TOOLS :: "NULLRAY_AGENT_TOOLS"
ENV_AGENT_STEPS :: "NULLRAY_AGENT_STEPS"
ENV_SESSION :: "NULLRAY_SESSION"
ENV_COMPACT_CHARS :: "NULLRAY_COMPACT_CHARS"
ENV_STREAM :: "NULLRAY_STREAM"
ENV_REASONING :: "NULLRAY_REASONING"
ENV_MAX_TOKENS :: "NULLRAY_MAX_TOKENS"
ENV_SHELL_ALLOW :: "NULLRAY_SHELL_ALLOW"
ENV_SHELL_DENY :: "NULLRAY_SHELL_DENY"
ENV_SHELL_CONFIRM :: "NULLRAY_SHELL_CONFIRM"
ENV_SHELL_AUTONOMY :: "NULLRAY_SHELL_AUTONOMY"
ENV_AUTONOMY :: "NULLRAY_AUTONOMY"
ENV_MODE :: "NULLRAY_MODE"
ENV_MODE_POLICY :: "NULLRAY_MODE_POLICY"
ENV_REVIEW :: "NULLRAY_REVIEW"
ENV_REVIEW_MODEL :: "NULLRAY_REVIEW_MODEL"
ENV_EPHEMERAL :: "NULLRAY_EPHEMERAL"
ENV_GROUP_CONTEXT :: "NULLRAY_GROUP_CONTEXT"
ENV_PERMS :: "NULLRAY_PERMS"
ENV_PRIVACY_REDACT :: "NULLRAY_PRIVACY_REDACT"
ENV_MEM_MAX_CHARS :: "NULLRAY_MEM_MAX_CHARS"
ENV_SECRETS_ALLOW :: "NULLRAY_SECRETS_ALLOW"
ENV_IMPROVE_MODEL :: "NULLRAY_IMPROVE_MODEL"
ENV_IMPROVE_MAX_TOKENS :: "NULLRAY_IMPROVE_MAX_TOKENS"
ENV_CACHE :: "NULLRAY_CACHE"
ENV_AUTO :: "NULLRAY_AUTO"
ENV_ATTACH_MAX :: "NULLRAY_ATTACH_MAX"

SKILLS_DIR :: "skills"
MAX_TOOL_FILE_BYTES :: 512_000
MAX_AGENT_STEPS :: 24
MAX_SHELL_OUTPUT_BYTES :: 64_000
SHELL_TIMEOUT_MS :: 30_000
COMPACT_CHARS_DEFAULT :: 48_000
MAX_GREP_MATCHES :: 200
MAX_GLOB_RESULTS :: 500
MAX_GROUP_CONTEXT_CHARS :: 12_000
MAX_SESSION_SEARCH :: 40
MAX_STREAMING_CHARS :: 200_000
MAX_PENDING_EVENTS :: 512
MAX_TRANSCRIPT_CHARS :: 400_000
DEFAULT_MEM_MAX_CHARS :: 600_000
DEFAULT_IMPROVE_MAX_TOKENS :: 512
MAX_IDENTICAL_TOOL_LOOPS :: 3
MAX_IDENTICAL_ASSISTANT_LOOPS :: 2

POLL_TIMEOUT_MS :: 50
HTTP_TIMEOUT_SEC :: 120
MAX_MESSAGES :: 256
MAX_MESSAGE_CHARS :: 200_000
MAX_INPUT_CHARS :: 16_384
STATUS_HOLD_SEC :: 6
SPINNER_FRAME_MS :: 80

DEFAULT_TERM_COLS :: 80
DEFAULT_TERM_ROWS :: 24
