// SPDX-License-Identifier: LicenseRef-QSL-1.0-0BSD
/*
Shared names paths timeouts defaults and size limits.
*/

package constants

APP_NAME :: "nullray"
VERSION :: "0.8.0"
BUILD_DATE :: #config(NULLRAY_BUILD_DATE, "unknown")
BUILD_TIME :: #config(NULLRAY_BUILD_TIME, "unknown")
// Short git SHA baked at make time. Empty when unset or not a git tree.
// Makefile must quote the define value so hex-like SHAs (7e1af7d) stay strings
// instead of being parsed as floats (7e1 = 70).
BUILD_COMMIT :: #config(NULLRAY_BUILD_COMMIT, "")
CONFIG_DIR_NAME :: "nullray"
CONFIG_FILE :: "config.ini"
MCP_CONFIG_FILE :: "mcp.json"

DEFAULT_PROVIDER :: "ollama"
DEFAULT_MODEL_OLLAMA :: "gemma3:4b"
DEFAULT_MODEL_LMSTUDIO :: "local-model"
DEFAULT_MODEL_LLAMACPP :: "local"
DEFAULT_MODEL_OPENROUTER :: "google/gemini-3.8-flash"
DEFAULT_MODEL_OPENCODE :: "big-pickle"
DEFAULT_MODEL_OPENAI :: "gpt-5.4-mini"
DEFAULT_MODEL_OPENAI_COMPAT :: "gpt-5.4-mini"

DEFAULT_OLLAMA_BASE :: "http://127.0.0.1:11434/v1"
DEFAULT_LMSTUDIO_BASE :: "http://127.0.0.1:1234/v1"
DEFAULT_LLAMACPP_BASE :: "http://127.0.0.1:8080/v1"
DEFAULT_OPENROUTER_BASE :: "https://openrouter.ai/api/v1"
DEFAULT_OPENCODE_BASE :: "https://opencode.ai/zen/v1"
DEFAULT_OPENCODE_GO_BASE :: "https://opencode.ai/zen/go/v1"
DEFAULT_OPENAI_BASE :: "https://api.openai.com/v1"

DEFAULT_MODEL_OPENCODE_GO :: "minimax-m2.5"
DEFAULT_MODEL_ANTHROPIC :: "claude-sonnet-5"
DEFAULT_MODEL_GEMINI :: "gemini-3.8-flash"
DEFAULT_MODEL_GROQ :: "qwen/qwen3.6-27b"
DEFAULT_MODEL_DEEPSEEK :: "deepseek-v4-flash"
DEFAULT_MODEL_MISTRAL :: "mistral-small-latest"
DEFAULT_MODEL_TOGETHER :: "meta-llama/Llama-3.3-70B-Instruct-Turbo"
DEFAULT_MODEL_FIREWORKS :: "accounts/fireworks/models/llama4-scout-instruct-basic"
DEFAULT_MODEL_XAI :: "grok-build-0.1"
DEFAULT_MODEL_AZURE :: "gpt-5.4-mini"
DEFAULT_MODEL_CEREBRAS :: "qwen-3.8-27b"
DEFAULT_MODEL_COHERE :: "command-a-plus-05-2026"
DEFAULT_MODEL_NVIDIA :: "meta/llama-3.3-70b-instruct"
DEFAULT_MODEL_DASHSCOPE :: "qwen3.7-plus"
DEFAULT_MAX_TOKENS :: 2048
DEFAULT_REASONING :: "low"

DEFAULT_ANTHROPIC_BASE :: "https://api.anthropic.com/v1"
DEFAULT_GEMINI_BASE :: "https://generativelanguage.googleapis.com/v1beta/openai"
DEFAULT_GROQ_BASE :: "https://api.groq.com/openai/v1"
DEFAULT_DEEPSEEK_BASE :: "https://api.deepseek.com/v1"
DEFAULT_MISTRAL_BASE :: "https://api.mistral.ai/v1"
DEFAULT_TOGETHER_BASE :: "https://api.together.xyz/v1"
DEFAULT_FIREWORKS_BASE :: "https://api.fireworks.ai/inference/v1"
DEFAULT_XAI_BASE :: "https://api.x.ai/v1"
DEFAULT_CEREBRAS_BASE :: "https://api.cerebras.ai/v1"
DEFAULT_COHERE_BASE :: "https://api.cohere.ai/compatibility/v1"
DEFAULT_NVIDIA_BASE :: "https://integrate.api.nvidia.com/v1"
DEFAULT_DASHSCOPE_BASE :: "https://dashscope.aliyuncs.com/compatible-mode/v1"


SKILLS_DIR :: "skills"
MODELS_FILE :: "models.json"
SUBAGENTS_DIR :: ".nullray"
LEASES_DIR :: ".nullray/leases"
KNOWLEDGE_DIR :: ".nullray/knowledge"
WORKTREES_DIR :: ".nullray/worktrees"
BOARD_DIR :: ".nullray/board"
WORKTREEINCLUDE_FILE :: ".nullray/worktreeinclude"
DEFAULT_PRINT_TIMEOUT_SEC :: 600
SCHEDULE_MIN_INTERVAL_SEC :: 60
SCHEDULE_MAX_JOBS :: 50
SCHEDULE_RECURRING_EXPIRE_DAYS :: 7
SCHEDULE_DEFAULT_MAX_FAILURES :: 3
SCHEDULED_FILE :: ".nullray/scheduled_tasks.json"
WATCH_DIR :: ".nullray/watch"
HEARTBEAT_FILE :: ".nullray/HEARTBEAT.md"
HEARTBEAT_DEFAULT_SEC :: 1800
TODO_DIR :: ".nullray/todos"
TODO_MAX_ITEMS :: 100
TODO_STALE_NUDGE_TURNS :: 2
SERVE_SOCK_NAME :: "nullray.sock"
SCRIPTTOOLS_DIR :: ".nullray/tools"
SEARCH_PROVIDERS_FILE :: "search_providers.json"
SEARCH_TIMEOUT_SEC :: 15
SEARCH_MAX_RESULTS :: 10
SEARCH_SNIPPET_CHARS :: 400
TASKS_DIR :: ".nullray/tasks"
COMMANDS_DIR :: "commands"
LINT_FILE :: "lint.json"
GGUF_TOOL_TEMP :: 0.2
GGUF_TOOL_REP_PENALTY :: 1.0
SAMPLES_MAX :: 16
VERIFY_DIFF_MAX_CHARS :: 24_000
OLLAMA_MIN_AGENT_CTX :: 16_384
PLANS_DIR :: ".nullray/plans"
ARTIFACTS_DIR :: ".nullray/artifacts"
TRACES_DIR :: ".nullray/traces"
HANDOFF_FILE :: ".nullray/HANDOFF.md"
PLAN_REWIND_DIR :: ".nullray/plan-rewind"
MAX_PLAN_FILE_BYTES :: 200_000
ARTIFACT_CHARS_DEFAULT :: 3_000
ARTIFACT_EXCERPT_CHARS :: 800
ARTIFACT_READ_LINES_DEFAULT :: 200
ARTIFACT_READ_BYTES_MAX :: 32_768
ARTIFACT_GC_MAX_BYTES :: 64 * 1024 * 1024
ARTIFACT_GC_MAX_AGE_DAYS :: 7
PROJECTION_USER_TURNS_DEFAULT :: 6
PROJECTION_TOOL_STUBS_DEFAULT :: 8
MAX_TOOL_FILE_BYTES :: 512_000
DEFAULT_FETCH_MAX_BYTES :: 512_000
MEDIA_MAX_BYTES_DEFAULT :: 15 * 1024 * 1024
MEDIA_TURNS_DEFAULT :: 2
MEDIA_MAX_PARTS :: 8
// OpenRouter /models can exceed 512KiB, list-models uses this larger cap.
DEFAULT_MODELS_MAX_BYTES :: 2_000_000
// models.dev catalog (api.json) powers per-model surface routing and /models enrichment.
MODELSDEV_URL :: "https://models.dev/api.json"
MODELSDEV_FILE :: "models.dev.json"
MODELSDEV_MAX_BYTES :: 12 * 1024 * 1024
MODELSDEV_TTL_SEC :: 24 * 60 * 60
MODELSDEV_FETCH_TIMEOUT_SEC :: 20
MAX_READ_FILE_CHARS :: 64_000
MAX_MAN_PAGE_CHARS :: 32_000
MAX_APROPOS_LINES :: 40
MAX_AGENTS_PROMPT_CHARS :: 12_000
MAX_MEMORY_PROMPT_CHARS :: 4_000
MAX_MEMORY_ENTRIES :: 128
MAX_MEMORY_KEY_CHARS :: 128
MAX_MEMORY_VALUE_CHARS :: 8_192
MEMORY_TOPIC_CHARS :: 500
MEMORY_LIST_PREVIEW_CHARS :: 80
MEMORY_COMPACT_STALE_LINES :: 64
MEMORY_STALE_DAYS :: 90
MEMORY_SEARCH_DEFAULT_LIMIT :: 20
MEMORY_SEARCH_MAX_LIMIT :: 50
DEFAULT_MAX_FILE_LINES :: 400
DEFAULT_WARN_FILE_LINES :: 250
DEFAULT_CHECKPOINT_KEEP :: 50
MEMORY_DIR :: ".nullray/memory"
RAG_DIR :: ".nullray/rag"
DEFAULT_EMBED_MODEL_OLLAMA :: "nomic-embed-text"
DEFAULT_EMBED_MODEL_OPENROUTER :: "openai/text-embedding-3-small"
DEFAULT_EMBED_MODEL_OPENAI :: "text-embedding-3-small"
RAG_INDEX_VERSION :: 1
RAG_MAX_CHUNKS :: 2048
RAG_MAX_CHUNK_CHARS :: 1200
RAG_MAX_CHUNK_CHARS_MINILM :: 512
RAG_CHUNK_OVERLAP :: 120
RAG_BATCH :: 16
RAG_TOP_K :: 6
RAG_PROMPT_CHARS :: 2000
RAG_MIN_SCORE :: 0.25
RAG_INDEX_BYTES :: 32 * 1024 * 1024
RAG_ARTIFACT_MAX_CHARS :: 50_000
RAG_ARTIFACT_INDEX_CHARS :: 8_000
RAG_EMBED_TIMEOUT_SEC :: 30
RAG_HYBRID_ALPHA :: 0.7
SHADOW_DIR :: ".nullray/shadow"
POLICY_FILE :: ".nullray/policy.json"
HOOKS_FILE :: "hooks.json"
MCP_PINS_DIR :: "mcp-pins"
CAVEATS_REF :: ".agents/references/caveats.md"
MAX_PLAN_STEPS_NOTE_CHARS :: 2_000
MAX_AGENT_STEPS :: 24
MAX_AUTO_AGENT_STEPS :: 80
MAX_SHELL_OUTPUT_BYTES :: 64_000
SHELL_TIMEOUT_MS :: 30_000
AUTO_SHELL_TIMEOUT_MS :: 300_000
MAX_SHELL_TIMEOUT_MS :: 900_000
PR_WATCH_MAX_SEC :: 1800
PR_WATCH_INTERVAL_MIN_SEC :: 10
DOCS_TIMEOUT_MS :: 15_000
DOCS_MAX_CAPTURE_BYTES :: 96_000
DEFAULT_ELEVATE_MAX_FAILS :: 2
DEFAULT_ELEVATE_LOCK_SECS :: 900
DEFAULT_ELEVATE_MODAL_SECS :: 120
COMPACT_CHARS_DEFAULT :: 48_000
COMPACT_KEEP_MESSAGES :: 8
COMPACT_SUMMARIZER_INPUT_CHARS :: 24_000
COMPACT_MAX_TOKENS :: 1024
TOOL_CLEAR_KEEP_DEFAULT :: 6
TOOL_CLEAR_STUB_PREFIX :: "[cleared:"
MAX_VERIFY_OUTPUT_BYTES :: 12_000
MAX_VERIFY_FAILS :: 3
MAX_VERIFY_FINDINGS :: 8
MAX_REVIEW_DIFF_CHARS :: 12_000
MAX_REVIEW_BOT_DIFF_CHARS :: 48_000
DEFAULT_REVIEW_BOT_MAX_TOKENS :: 4096
MAX_GREP_MATCHES :: 200
MAX_GLOB_RESULTS :: 500
MAX_GROUP_CONTEXT_CHARS :: 12_000
MAX_SESSION_SEARCH :: 40
MAX_STREAMING_CHARS :: 200_000
MAX_STREAM_ERROR_BYTES :: 64_000
MAX_PENDING_EVENTS :: 512
MAX_TRANSCRIPT_CHARS :: 400_000
DEFAULT_MEM_MAX_CHARS :: 600_000
DEFAULT_IMPROVE_MAX_TOKENS :: 512
MAX_IDENTICAL_TOOL_LOOPS :: 3
MAX_IDENTICAL_ASSISTANT_LOOPS :: 2
DEFAULT_SUBAGENT_MAX :: 3
DEFAULT_SUBAGENT_DEPTH :: 1
DEFAULT_SPECULATE_PARALLEL :: 2
DEFAULT_LOCATE_STEPS :: 4
DEFAULT_LOCATE_PARALLEL :: 8
DEFAULT_LOCATE_MAX_CITES :: 12
MAX_LOCATE_STEPS :: 8
MAX_ARCHITECT_STEPS :: 8
MAX_LOCATE_PARALLEL :: 8
MAX_LOCATE_MAX_CITES :: 32
MAX_REPO_MAP_BYTES :: 12_288
MAX_REPO_MAP_DEPTH :: 3
DEFAULT_REPO_MAP_DEPTH :: 2
MAX_CHILD_RESULT_CHARS :: 4_000
MAX_HUNT_EXPLORE_CHARS :: 4_000

MAX_COORD_PREAMBLE_CHARS :: 4_000
MAX_KNOWLEDGE_VALUE_CHARS :: 2_000
MAX_KNOWLEDGE_DIGEST_CHARS :: 2_000
MAX_KNOWLEDGE_ENTRIES :: 256
LEASE_TTL_SEC :: 900
LEASE_HEARTBEAT_SEC :: 60
MAX_PEER_MESSAGE_CHARS :: 1_000
MAX_BOARD_ITEMS :: 128

POLL_TIMEOUT_MS :: 50
SHUTDOWN_JOIN_MS :: 3_000
HTTP_TIMEOUT_SEC       :: 120
// Local inference on CPU needs a longer floor than remote APIs.
HTTP_TIMEOUT_SEC_LOCAL :: 600
HTTP_RETRIES_DEFAULT :: 3
MAX_MESSAGES :: 256
MAX_MESSAGE_CHARS :: 200_000
MAX_INPUT_CHARS :: 16_384
STDIN_CONTEXT_MAX_CHARS :: 32_000
STATUS_HOLD_MS :: 1200
STREAM_REVEAL_CHARS :: 10
STREAM_REVEAL_THINK_CHARS :: 6
INPUT_HISTORY_MAX :: 64
INPUT_MAX_ROWS :: 8
SPINNER_FRAME_MS :: 80
DEFAULT_TERM_COLS :: 80
DEFAULT_TERM_ROWS :: 24

// External harness CLIs (harness_run / harness_list tools).
HARNESSES_FILE :: "harnesses.json"
HARNESS_TIMEOUT_SEC :: 600
HARNESS_MAX_OUTPUT :: 60_000
HARNESS_MAX_TIMEOUT_SEC :: 1800

// Malformed tool call retry budget before the model is told to give up tools.
TOOL_RETRY_DEFAULT :: 2
TOOL_RETRY_MAX :: 5

// Hybrid loop detection sliding window and thresholds.
// Defaults leave room for multi-file scaffolds before warn/steer/stop.
LOOP_WINDOW_DEFAULT :: 10
LOOP_WINDOW_MAX :: 32
LOOP_FUZZY_DEFAULT :: 0.88
LOOP_STAGNATION_DEFAULT :: 5
LOOP_SEM_THRESHOLD_DEFAULT :: 0.85
// Warn count before the detector steers, then stops the turn.
LOOP_STEER_FIRES :: 3
LOOP_STOP_FIRES :: 5

// SWE-Protege escalation: cap escalated chat calls per turn.
ESCALATE_MAX_DEFAULT :: 3
ESCALATE_MAX_CAP :: 8

// Per-model smoke probe: single canned tool-call chat.
MODEL_SMOKE_MAX_TOKENS :: 256

// Model profiles file (per-family settings: ctx, temp, tools posture).
MODEL_PROFILES_FILE :: "model_profiles.json"
