// SPDX-License-Identifier: LicenseRef-QSL-1.0-0BSD
package main

import "core:fmt"
import "nullray:constants"

print_version :: proc() {
	fmt.printf("%s %s (built %s %s)\n", constants.APP_NAME, constants.VERSION, constants.BUILD_DATE, constants.BUILD_TIME)
}

print_help :: proc() {
	print_version()
	fmt.println("usage: nullray [options] [prompt...]")
	fmt.println("")
	fmt.println("options:")
	fmt.println("  -h, --help              show this help")
	fmt.println("  -V, --version           show version and build stamp")
	fmt.println("  -e, --ephemeral         do not load or save session transcripts")
	fmt.println("  -t, --self-test         headless smoke (tools, mcp, draw, shell deny)")
	fmt.println("      --audit             run workspace security scanners and exit (1 if any high)")
	fmt.println("      --review            local VCS review bot (Git/Fossil, no forge)")
	fmt.println("      --review-scope S    working | staged | unstaged | base")
	fmt.println("      --base REF          review vs branch/revision (implies base scope)")
	fmt.println("      --staged            review staged/index changes only")
	fmt.println("      --unstaged          review unstaged working-tree changes only")
	fmt.println("      --include-untracked include untracked files in working/unstaged review")
	fmt.println("      --paths LIST        comma-separated path filters for --review")
	fmt.println("      --doctor            print env, TTY, and latest crash dump path")
	fmt.println("      --debug             verbose stderr logs (also NULLRAY_DEBUG=1)")
	fmt.println("  -P, --print             one-shot agent (no TUI), print reply and exit")
	fmt.println("      --stream            stream reply tokens live in print mode")
	fmt.println("      --trace             stderr tool-call lines in print mode")
	fmt.println("      --patch-out PATH    write a unified diff of run changes")
	fmt.println("      --no-adopt          do not import keys/config from other AI CLIs")
	fmt.println("  -q, --ask               simple Q&A (print + ask + ephemeral, read-only tools)")
	fmt.println("      --acp               run Agent Client Protocol server over stdio (editors)")
	fmt.println("      --serve             run the shared agent daemon on a unix socket")
	fmt.println("                          (also: nullray serve; socket: NULLRAY_SERVE_SOCK)")
	fmt.println("      --connect           with --print, run the prompt on a running daemon")
	fmt.println("                          (NULLRAY_CONNECT; plain --print is unchanged)")
	fmt.println("  attach [SESSION]        attach to a daemon session and stream updates")
	fmt.println("  watch add|list|rm|show  standing watches on durable schedules,")
	fmt.println("                          e.g. watch add \"every 2h\" \"check X\"")
	fmt.println("  -p, --provider ID       ollama | lmstudio | llamacpp | openai |")
	fmt.println("                          openai-compat | openrouter | opencode |")
	fmt.println("                          opencode-go | anthropic | gemini | groq |")
	fmt.println("                          deepseek | mistral | together | fireworks |")
	fmt.println("                          xai | azure")
	fmt.println("  -m, --model NAME        override default model")
	fmt.println("      --theme NAME        ink | ember | moss | slate | rose | mono | dusk")
	fmt.println("      --mode MODE         ask | plan | review | edit | orchestrate")
	fmt.println("      --hunt [PROFILE]    vuln hunt auto|balanced|explore|oracle|adversarial (sets review)")
	fmt.println("      --perms POLICY      ask | allow | yolo")
	fmt.println("      --gate LEVEL        0..3 or ask|allow|yolo (tool capability)")
	fmt.println("      --sandbox MODE      off | soft | warn | strict | on")
	fmt.println("      --askpass            sudo/doas askpass helper (internal)")
	fmt.println("      --elevate-broker P   run privilege broker on path (internal)")
	fmt.println("      --no-elevate         deny elevated commands (NULLRAY_ELEVATE=deny)")
	fmt.println("  -w, --workspace PATH    workspace root for tools/sandbox")
	fmt.println("      --session NAME      resume or create named session")
	fmt.println("      --list-sessions     list saved sessions and exit")
	fmt.println("      --inspect-session [NAME]  print session summary (name, meta, preview)")
	fmt.println("      --follow            with --inspect-session, tail new transcript lines")
	fmt.println("      --search-sessions Q search session names and text")
	fmt.println("      --delete-session N  delete a named session")
	fmt.println("      --rename-session N  rename session (needs --as NEW, optional --force)")
	fmt.println("      --export-session N  export session to --out DIR")
	fmt.println("      --import-session P  import session from path or dir")
	fmt.println("      --as NAME           name for --import-session or --rename-session")
	fmt.println("      --force             overwrite destination on --rename-session")
	fmt.println("      --list-modules      list compiled-in modules and exit")
	fmt.println("      --list-skills       list loaded skills and exit")
	fmt.println("      --skills PATH       extra skill root(s), comma-separated (repeatable)")
	fmt.println("      --keys PRESET       default | neovim | emacs")
	fmt.println("      --message-file PATH prompt from file (print mode)")
	fmt.println("      --image PATH        attach an image (repeatable)")
	fmt.println("      --audio PATH        attach an audio file (repeatable)")
	fmt.println("      --video PATH        attach a video file (repeatable)")
	fmt.println("      --media PATH        attach media, kind from extension")
	fmt.println("      --out PATH          write final reply to file (or export dir)")
	fmt.println("      --plan-out PATH     plan mode artifact path")
	fmt.println("      --plan-in PATH      load Done Contract and apply (print edit)")
	fmt.println("      --output-format F   text | json (print mode)")
	fmt.println("      --print-strict      exit 1 on incomplete plan/verify/living subagents")
	fmt.println("      --auto              autonomous edit (NULLRAY_AUTO=1, 80 steps)")
	fmt.println("      --usage             print token/cost summary (print mode)")
	fmt.println("      --samples N         best-of-N print runs, pick by verifier")
	fmt.println("      --architect         architect model plans, editor model executes")
	fmt.println("      --timeout SEC       print-mode wall clock limit (default 600)")
	fmt.println("      --bare              skip home MCP and non-workspace skills")
	fmt.println("                          (NULLRAY_SKILLS / --skills still load)")
	fmt.println("      --fail-on-findings  exit 1 when review FINDINGS: N > 0 (also --review)")
	fmt.println("      --no-splash         skip startup splash")
	fmt.println("      --no-subagents      disable subagent task tool")
	fmt.println("      --splash            force startup splash")
	fmt.println("      --hide-sensitive    hide account and API key balances")
	fmt.println("      --list-models       list models for active provider and exit")
	fmt.println("      --probe-tools [P/M] probe tool-name spellings a model emits, save aliases")
	fmt.println("      --completions SHELL print completion script and exit")
	fmt.println("      --man               print man page source and exit")
	fmt.println("")
	fmt.println("print mode defaults: ephemeral session, mode ask (edit when --plan-in).")
	fmt.println("edit under print needs --perms allow|yolo. Pipe stdin when not a TTY.")
	fmt.println("plan-in applies a Done Contract: empty prompt becomes Execute the approved plan.")
	fmt.println("--review reviews local Git/Fossil diffs (working/staged/unstaged/base). No forge required.")
	fmt.println("")
	fmt.println("env file:  ~/.config/nullray/env")
	fmt.println("env vars:  NULLRAY_PROVIDER NULLRAY_MODEL NULLRAY_THEME NULLRAY_MODE NULLRAY_PERMS")
	fmt.println("           NULLRAY_HUNT NULLRAY_TEMPERATURE NULLRAY_TOP_P NULLRAY_HUNT_REASONING")
	fmt.println("           NULLRAY_SANDBOX NULLRAY_WORKSPACE NULLRAY_SESSION NULLRAY_EPHEMERAL")
	fmt.println("           NULLRAY_SPLASH NULLRAY_KEYS NULLRAY_STREAM OPENROUTER_API_KEY")
	fmt.println("           NULLRAY_HTTP_RETRIES NULLRAY_FALLBACK_MODELS NULLRAY_OPENROUTER_IGNORE")
	fmt.println("           NULLRAY_MCP_ALLOW_ANY NULLRAY_MCP_APPROVE_DRIFT NULLRAY_WORKSPACE_TRUST")
	fmt.println("           NULLRAY_HIDE_SENSITIVE NULLRAY_BARE NULLRAY_PRINT_TIMEOUT NULLRAY_OUT")
	fmt.println("           NULLRAY_PRINT_STRICT NULLRAY_PRINT_USAGE NULLRAY_USAGE NULLRAY_USAGE_PERSIST")
	fmt.println("           NULLRAY_PLAN_OUT NULLRAY_PLAN_IN NULLRAY_REVIEW_SCOPE NULLRAY_REVIEW_BASE")
	fmt.println("           NULLRAY_REVIEW_PATHS NULLRAY_COLOR NULLRAY_ALT_SCREEN NULLRAY_MOUSE")
	fmt.println("           NULLRAY_DEBUG OPENAI_API_KEY OPENAI_BASE_URL OLLAMA_HOST")
	fmt.println("           NULLRAY_MEDIA NULLRAY_MEDIA_MAX NULLRAY_MEDIA_TURNS")
	fmt.println("           NULLRAY_CONNECT NULLRAY_SERVE_SOCK")
	fmt.println("           NULLRAY_COLLAPSE")
	fmt.println("           LM_STUDIO_HOST LM_API_TOKEN LLAMA_CPP_HOST LLAMA_CPP_API_KEY")
	fmt.println("           NULLRAY_HTTP_TIMEOUT NULLRAY_SANDBOX_PORTS NULLRAY_PROMPT NULLRAY_JUDGE NULLRAY_JSON_MODE")
	fmt.println("")
	fmt.println("completions: nullray --completions bash|zsh|fish|powershell|elvish|nushell")
	fmt.println("man page:    nullray --man | man -l -")
}
