// Code generated by scripts/gen_modules.odin; DO NOT EDIT.
package main

import _ "nullray:modules/clock"

when ODIN_OS != .Windows {
	foreign import cmod_hello_c "../../nullray/modules/hello_c/mod.o"
	foreign cmod_hello_c {
		nullray_hello_c_module_init :: proc() ---
	}

	@(init)
	cmod_hello_c_boot :: proc "contextless" () {
		nullray_hello_c_module_init()
	}
}

