// SPDX-License-Identifier: LicenseRef-QSL-1.0-0BSD
/*
Generate cmd/nullray/modules_gen.odin: one side-effect import per
nullray/modules/<id>/ directory that contains a mod.odin. Replaces the old
python generator so the build needs only Odin plus a C toolchain.

Run: odin run scripts/gen_modules.odin -file
*/

package main

import "core:fmt"
import "core:os"
import "core:path/filepath"
import "core:sort"
import "core:strings"

main :: proc() {
	mod_dir := "nullray/modules"
	out_path := "cmd/nullray/modules_gen.odin"

	ids := make([dynamic]string, context.temp_allocator)
	entries, derr := os.read_all_directory_by_path(mod_dir, context.temp_allocator)
	if derr == nil {
		defer os.file_info_slice_delete(entries, context.temp_allocator)
		for e in entries {
			if e.type != .Directory {
				continue
			}
			mod_file, _ := filepath.join({mod_dir, e.name, "mod.odin"}, context.temp_allocator)
			if os.is_file(mod_file) {
				append(&ids, strings.clone(e.name, context.temp_allocator))
			}
		}
	}
	sort.quick_sort(ids[:])

	b := strings.builder_make(context.temp_allocator)
	strings.write_string(&b, "// Code generated by scripts/gen_modules.odin; DO NOT EDIT.\n")
	strings.write_string(&b, "package main\n\n")
	for id in ids {
		fmt.sbprintf(&b, "import _ \"nullray:modules/%s\"\n", id)
	}
	strings.write_byte(&b, '\n')
	body := strings.to_string(b)

	if old, err := os.read_entire_file(out_path, context.temp_allocator); err == nil {
		if string(old) == body {
			return
		}
	}
	if err := os.write_entire_file(out_path, transmute([]u8)body); err != nil {
		fmt.eprintln("gen_modules: cannot write", out_path)
		os.exit(1)
	}
	fmt.println("modules_gen:", len(ids), "module(s):", len(ids) > 0 ? strings.join(ids[:], ", ", context.temp_allocator) : "none")
}
