#!/usr/bin/env python3
"""Generate cmd/nullray/modules_gen.odin: one side-effect import per
nullray/modules/<id>/ directory that contains a mod.odin."""
import os, sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
MOD_DIR = os.path.join(ROOT, "nullray", "modules")
OUT = os.path.join(ROOT, "cmd", "nullray", "modules_gen.odin")

ids = []
if os.path.isdir(MOD_DIR):
    for entry in sorted(os.listdir(MOD_DIR)):
        if os.path.isfile(os.path.join(MOD_DIR, entry, "mod.odin")):
            ids.append(entry)

lines = [
    "// Code generated by scripts/gen_modules.py; DO NOT EDIT.",
    "package main",
    "",
]
for mid in ids:
    lines.append(f'import _ "nullray:modules/{mid}"')
lines.append("")
body = "\n".join(lines)
if os.path.isfile(OUT) and open(OUT).read() == body:
    sys.exit(0)
with open(OUT, "w") as f:
    f.write(body)
print(f"modules_gen: {len(ids)} module(s): {', '.join(ids) or 'none'}")
