// SPDX-License-Identifier: LicenseRef-QSL-1.0-0BSD
/*
Generate cmd/nullray/modules_gen.odin: a side-effect import per
nullray/modules/<id>/ with mod.odin, plus foreign glue per mod.c.
Run: odin run scripts/gen_modules.odin -file
*/

package main

import "core:fmt"
import "core:os"
import "core:path/filepath"
import "core:sort"
import "core:strings"

when ODIN_OS == .Windows {
	OBJ_EXT :: ".obj"
} else {
	OBJ_EXT :: ".o"
}

@(private)
valid_id :: proc(id: string) -> bool {
	if len(id) == 0 {
		return false
	}
	for c in id {
		ok := (c >= 'a' && c <= 'z') || (c >= '0' && c <= '9') || c == '_'
		if !ok {
			return false
		}
	}
	return true
}

main :: proc() {
	mod_dir := "nullray/modules"
	out_path := "cmd/nullray/modules_gen.odin"
	c_out_path := "cmd/nullray/modules_gen_c.odin"

	odin_ids := make([dynamic]string, context.temp_allocator)
	c_ids := make([dynamic]string, context.temp_allocator)
	entries, derr := os.read_all_directory_by_path(mod_dir, context.temp_allocator)
	if derr == nil {
		defer os.file_info_slice_delete(entries, context.temp_allocator)
		for e in entries {
			if e.type != .Directory {
				continue
			}
			if !valid_id(e.name) {
				fmt.eprintln("gen_modules: skipping", e.name, "- id must be [a-z0-9_]")
				continue
			}
			odin_file, _ := filepath.join({mod_dir, e.name, "mod.odin"}, context.temp_allocator)
			c_file, _ := filepath.join({mod_dir, e.name, "mod.c"}, context.temp_allocator)
			if os.is_file(odin_file) {
				append(&odin_ids, strings.clone(e.name, context.temp_allocator))
			}
			if os.is_file(c_file) {
				append(&c_ids, strings.clone(e.name, context.temp_allocator))
			}
		}
	}
	sort.quick_sort(odin_ids[:])
	sort.quick_sort(c_ids[:])

	b := strings.builder_make(context.temp_allocator)
	strings.write_string(&b, "// Code generated by scripts/gen_modules.odin; DO NOT EDIT.\n")
	strings.write_string(&b, "package main\n\n")

	for id in odin_ids {
		fmt.sbprintf(&b, "import _ \"nullray:modules/%s\"\n", id)
	}
	if len(odin_ids) > 0 && len(c_ids) > 0 {
		strings.write_byte(&b, '\n')
	}

	// C modules foreign-link compiled objects and call the entry point from
	// @(init). They live in a second generated file gated to POSIX targets
	// because Windows object linking is not verified yet.
	cb := strings.builder_make(context.temp_allocator)
	strings.write_string(&cb, "#+build !windows\n")
	strings.write_string(&cb, "// Code generated by scripts/gen_modules.odin; DO NOT EDIT.\n")
	strings.write_string(&cb, "package main\n\n")
	for id in c_ids {
		fmt.sbprintf(&cb,
			"foreign import cmod_%s \"../../nullray/modules/%s/mod.o\"\n",
			id, id)
		fmt.sbprintf(&cb, "foreign cmod_%s {{\n\tnullray_%s_module_init :: proc() ---\n}}\n\n", id, id)
		fmt.sbprintf(&cb,
			"@(init)\ncmod_%s_boot :: proc \"contextless\" () {{\n\tnullray_%s_module_init()\n}}\n\n",
			id, id)
	}

	body := strings.to_string(b)
	if old, err := os.read_entire_file(out_path, context.temp_allocator); err == nil {
		if string(old) == body {
			return
		}
	}
	if err := os.write_entire_file(out_path, transmute([]u8)body); err != nil {
		fmt.eprintln("gen_modules: cannot write", out_path)
		os.exit(1)
	}
	cbody := strings.to_string(cb)
	if err := os.write_entire_file(c_out_path, transmute([]u8)cbody); err != nil {
		fmt.eprintln("gen_modules: cannot write", c_out_path)
		os.exit(1)
	}
	total := len(odin_ids) + len(c_ids)
	fmt.println("modules_gen:", total, "module(s)")
}
