#compdef nullray
_nullray() {
  local -a opts providers modes perms sandboxes shells themes
  opts=(
    '--help[show help]' '-h[show help]'
    '--version[show version]' '-V[show version]'
    '--ephemeral[do not load or save transcripts]' '-e[do not load or save transcripts]'
    '--self-test[headless smoke]' '-t[headless smoke]'
    '--audit[run workspace security scanners]'
    '--doctor[print env and crash dump paths]'
    '--debug[verbose stderr lifecycle logs]'
    '--print[one-shot agent no TUI]' '-P[one-shot agent no TUI]'
    '--ask[simple Q and A]' '-q[simple Q and A]'
    '--bare[skip home MCP and non-workspace skills]'
    '--fail-on-findings[exit 1 when review findings present]'
    '--provider[provider id]:provider:(ollama lmstudio openai openai-compat openrouter opencode opencode-go anthropic gemini groq deepseek mistral together fireworks xai azure)'
    '-p[provider id]:provider:(ollama lmstudio openai openai-compat openrouter opencode opencode-go anthropic gemini groq deepseek mistral together fireworks xai azure)'
    '--model[model id]:model:'
    '-m[model id]:model:'
    '--theme[ui theme]:theme:(ink ember moss slate rose mono dusk)'
    '--mode[agent mode]:mode:(ask plan review edit)'
    '--perms[shell policy]:perms:(ask allow yolo)'
    '--sandbox[sandbox mode]:sandbox:(off soft warn strict on)'
    '--workspace[workspace path]:dir:_files -/'
    '-w[workspace path]:dir:_files -/'
    '--session[session name]:session:'
    '--list-sessions[list saved sessions]'
    '--search-sessions[search sessions]:query:'
    '--delete-session[delete named session]:session:'
    '--export-session[export session to --out dir]:session:'
    '--import-session[import session from path]:path:_files'
    '--as[import or install destination name]:name:'
    '--list-skills[list loaded skills]'
    '--install-skill[install skill .md or package]:path:_files'
    '--uninstall-skill[uninstall config skill]:id:'
    '--skills[extra skill root dirs]:path:_files -/'
    '--keys[keybind preset]:keys:(default neovim emacs)'
    '--message-file[prompt file]:file:_files'
    '--out[write final reply or export dir]:file:_files'
    '--plan-out[plan artifact path]:file:_files'
    '--plan-in[load Done Contract plan]:file:_files'
    '--output-format[print output format]:format:(text json)'
    '--print-strict[strict print exit codes]'
    '--auto[autonomous edit mode]'
    '--usage[print token usage summary]'
    '--timeout[print timeout seconds]:seconds:'
    '--no-splash[skip startup splash]' \
    '--no-subagents[disable subagent task tool]' \
    '--splash[force startup splash]'
    '--hide-sensitive[hide account and API key balances]'
    '--list-models[list models for active provider]'
    '--completions[print shell completions]:shell:(bash zsh fish powershell elvish nushell)'
    '--man[print man page source]'
  )
  _arguments -s : $opts
}
compdef _nullray nullray
