#compdef nullray
_nullray() {
  local -a opts providers modes perms sandboxes shells themes
  opts=(
    '--help[show help]' '-h[show help]'
    '--version[show version]' '-V[show version]'
    '--ephemeral[do not load or save transcripts]' '-e[do not load or save transcripts]'
    '--self-test[headless smoke]' '-t[headless smoke]'
    '--audit[run workspace security scanners]'
    '--review[local VCS review bot]'
    '--review-scope[review scope]:scope:(working staged unstaged base)'
    '--base[base revision for review]:ref:'
    '--staged[review staged changes only]'
    '--unstaged[review unstaged changes only]'
    '--include-untracked[include untracked files in review]'
    '--paths[comma-separated review path filters]:paths:'
    '--doctor[print env and crash dump paths]'
    '--debug[verbose stderr lifecycle logs]'
    '--print[one-shot agent no TUI]' '-P[one-shot agent no TUI]'
    '--stream[stream reply tokens live]'
    '--trace[stderr tool-call lines]'
    '--patch-out[write unified diff of run changes]:file:_files'
    '--no-adopt[skip foreign config adoption]'
    '--ask[simple Q and A]' '-q[simple Q and A]'
    '--acp[ACP server over stdio]'
    '--serve[shared agent daemon on a unix socket]'
    '--connect[route --print through a running daemon]'
    '--attach[attach to a daemon session]'
    '--bare[skip home MCP and non-workspace skills]'
    '--fail-on-findings[exit 1 when review findings present]'
    '--provider[provider id]:provider:(ollama lmstudio llamacpp openai openai-compat openrouter opencode opencode-go anthropic gemini groq deepseek mistral together fireworks xai azure cerebras cohere nvidia dashscope)'
    '-p[provider id]:provider:(ollama lmstudio llamacpp openai openai-compat openrouter opencode opencode-go anthropic gemini groq deepseek mistral together fireworks xai azure cerebras cohere nvidia dashscope)'
    '--model[model id]:model:'
    '-m[model id]:model:'
    '--theme[ui theme]:theme:(ink ember moss slate rose mono dusk)'
    '--mode[agent mode]:mode:(ask plan review edit orchestrate)'
    '--hunt[vuln hunt profile]:profile:(auto balanced explore oracle adversarial)'
    '--perms[shell policy]:perms:(ask allow yolo)'
    '--gate[tool gate]:gate:(0 1 2 3 ask allow yolo)'
    '--sandbox[sandbox mode]:sandbox:(off soft warn strict on)'
    '--workspace[workspace path]:dir:_files -/'
    '-w[workspace path]:dir:_files -/'
    '--session[session name]:session:'
    '--list-sessions[list saved sessions]'
    '--search-sessions[search sessions]:query:'
    '--delete-session[delete named session]:session:'
    '--rename-session[rename named session]:session:'
    '--force[overwrite on rename]'
    '--export-session[export session to --out dir]:session:'
    '--import-session[import session from path]:path:_files'
    '--as[import or install destination name]:name:'
    '--list-skills[list loaded skills]'
    '--skills[extra skill root dirs]:path:_files -/'
    '--keys[keybind preset]:keys:(default neovim emacs)'
    '--message-file[prompt file]:file:_files'
    '--image[attach image]:file:_files'
    '--audio[attach audio]:file:_files'
    '--video[attach video]:file:_files'
    '--media[attach media file]:file:_files'
    '--out[write final reply or export dir]:file:_files'
    '--plan-out[plan artifact path]:file:_files'
    '--plan-in[load Done Contract plan]:file:_files'
    '--output-format[print output format]:format:(text json)'
    '--print-strict[strict print exit codes]'
    '--auto[autonomous edit mode]'
    '--usage[print token usage summary]'
    '--timeout[print timeout seconds]:seconds:'
    '--no-splash[skip startup splash]' \
    '--no-subagents[disable subagent task tool]' \
    '--splash[force startup splash]'
    '--hide-sensitive[hide account and API key balances]'
    '--list-models[list models for active provider]'
    '--completions[print shell completions]:shell:(bash zsh fish powershell elvish nushell)'
    '--man[print man page source]'
  )
  _arguments -s : $opts
}
compdef _nullray nullray
